### PR TITLE
Fix provider lock-in after aborted login; simplify auth modules

### LINKED ISSUE #1529: APP, CMS: Simplify Auth logic

### PR DESCRIPTION
**Pull request by MrDirkelz**
Was not really happy with the state of the auth.ts files for the cms and app. So just a last simplification and it also solves a bug.

### CODE REVIEW

File: app/src/auth.ts [hunk 1]
```diff
@@ -1,61 +1,74 @@
...
 import * as Sentry from "@sentry/vue";
 import { setCustomHeader, removeCustomHeader, getSocket } from "luminary-shared";
 import { db, DocType } from "luminary-shared";
 import type { AuthProviderDto } from "luminary-shared";
 
-/** Ref for the currently active OAuth provider document id (or null when unauthenticated). Used by shared HTTP to send x-auth-provider-id. */
+const AUTH0_CACHE_PREFIX = "@@auth0spajs@@::";
+const AUTH0_TX_PREFIX = "a0.spajs.";
+const AUTH0_TX_KEY_PREFIX = "a0.spajs.txs.";
+
```
Comment (ivanslabbert) [inline app/src/auth.ts:13]: New ticket: Move to authProviderDto

**Review by ivanslabbert — APPROVED** [review]
Approved with one comment
