### PR TITLE
CMS: Review and implement fixes/enhancements in editor pages and overviews

### LINKED ISSUE #1439: CMS: Visual review of admin screens (overviews - editing)

### PR DESCRIPTION
**Pull request by ChrisTouo**
image

Icons in the top bar not aligned on the sides with the content

image

Back button misplaced in the language editor

### CODE REVIEW

**Comment by ChrisTouo** [comment]
image

To fix: when the sidebar opens in mobile mode the content behind is pushed at the bottom

**Review by MrDirkelz — COMMENTED** [review]
This looks fine to me, just one nitpick

**Comment by ChrisTouo** [comment]
- [x] outline icon for delete button
 - [x] Add padding on burger menu
 - [x] check the text color im desktop mode for the dropdown
 - [x]  Check the failing test 
 - [x]  Check vue warnings

File: cms/src/components/BasePage.vue [hunk 1]
```diff
@@ -38,30 +39,33 @@ const isMobileScreen = breakpoints.smaller("lg");
...
-                    class="pl-2.5 text-zinc-500"
+                    class="text-zinc-500 max-sm:ml-5"
                     @click="
-                        !isEditContentPage
-                            ? onOpenMobileSidebar?.()
-                            : router.push({ name: 'overview' })
+                        () => {
+                            if (isEditContentPage) router.push({ name: 'overview' });
+                            else if (isEditLanguagePage) router.push({ name: 'languages' });
+                            else onOpenMobileSidebar?.();
```
Comment (MrDirkelz) [inline cms/src/components/BasePage.vue:57]: We should perhaps create a ticket to simplify this in a helper function later - otherwise if we start to add more pages this will be one massive if clause, and long if clauses create performance issues once they become bigger (mainly on nested if statements, but same can count for these types

**Review by ivanslabbert — APPROVED** [review]
