### PR TITLE
fix: Adjust language selector behavior and layout in EditContent components

### LINKED ISSUE #1143: CMS: Translation Selector Bug fixes
Bug: Sometimes have to refresh to get the translation selector to collapse

### PR DESCRIPTION
**Pull request by MrDirkelz**

### CODE REVIEW

File: cms/src/components/content/EditContent.vue [hunk 1]
```diff
@@ -595,7 +596,7 @@ const isLocalChange = db.isLocalChangeAsRef(parentId);
         <div class="flex flex-col gap-0 lg:h-full lg:flex-row lg:gap-2 lg:overflow-y-hidden">
             <!-- sidebar -->
             <div class="w-full flex-shrink-0 lg:h-full lg:w-[336px]" v-if="editableParent">
-                <div class="overflow-y-auto scrollbar-hide lg:h-full lg:pb-2">
+                <div class="scrollbar-hide lg:overflow-y-auto lg:h-full lg:pb-2">
```
Comment (johan-bell) [inline cms/src/components/content/EditContent.vue]: why moving it around ?

**Review by johan-bell — COMMENTED** [review]
Just one comment and fix the conflicts please.

File: cms/src/components/content/EditContent.vue (hunk 1 above)
Comment (MrDirkelz) [reply cms/src/components/content/EditContent.vue]: To fix a visual bug

**Review by ChrisTouo — COMMENTED** [review]
👍👍

**Review by ivanslabbert — COMMENTED** [review]
Fix merge conflicts

**Comment by MrDirkelz** [comment]
image

File: cms/src/components/content/EditContent.vue [hunk 2]
```diff
@@ -685,6 +690,10 @@ const isLocalChange = useDexieLiveQuery(
                                 :existingParent="existingParent"
                                 @updateIsValid="(val) => (isValid = val)"
                                 @create-translation="(language) => createTranslation(language)"
+                                @update:selectorCollapsed="
+                                    (val) => (isLanguageSelectorCollapsed = val)
+                                "
+                                @update:selectorHeight="(val) => (languageSelectorHeight = val)"
                             />
```
Comment (johan-bell) [inline cms/src/components/content/EditContent.vue]: These inline handlers assign into isLanguageSelectorCollapsed / languageSelectorHeight from script ref()s. Inside an arrow in the template, confirm the compiler updates the ref (.value) correctly; if sticky offset or height ever look stuck in QA, switch to small script functions, e.g. (v) => { isLanguageSelectorCollapsed.value = v }, for clarity and safety.

File: cms/src/components/BasePage.vue [hunk 3]
```diff
@@ -143,6 +144,7 @@ const isMobileScreen = breakpoints.smaller("lg");
                 <slot name="internalPageHeader" />
             </div>
             <div
+                data-scroll-container
                 class="min-h-0 flex-1 overflow-y-auto scrollbar-hide"
                 :class="[
```
Comment (johan-bell) [inline cms/src/components/BasePage.vue:148]: `data-topbar` is used for measurements in the edit flow; I don’t see `[data-scroll-container]` referenced in this PR. If nothing queries it yet, consider removing it to avoid dead attributes, or add a short comment / test hook if it’s intentional for a follow-up maybe ?

File: cms/src/components/content/EditContentParentValidation.vue [hunk 4]
```diff
@@ -54,34 +58,53 @@ const checkTopbarCollision = () => {
...
 onMounted(() => {
     // Run on small screens or when testing
     if (!isSmallScreen.value && import.meta.env.MODE !== "test") return;
 
-    // Add window scroll listener for topbar collision check
-    window.addEventListener("scroll", checkTopbarCollision, { passive: true });
-
-    // Also listen to any scroll events that might affect positioning
+    // Listen during capture phase so it fires even when scroll propagation is stopped
     document.addEventListener("scroll", checkTopbarCollision, { passive: true, capture: true });
```
Comment (johan-bell) [inline cms/src/components/content/EditContentParentValidation.vue:88]: document + capture: true will see many scroll events. Likely fine with { passive: true } and a small getBoundingClientRect path, but if we ever see jank on low-end mobile, consider requestAnimationFrame throttling or attaching to the scroll container ([data-scroll-container]) if that matches the actual scroll surface on small screens.

Comment (johan-bell) [reply cms/src/components/content/EditContentParentValidation.vue:88]: Is this not an issue ? We can resolve it @MrDirkelz ?

**Review by johan-bell — APPROVED** [review]
Check non resolved comment before merging @MrDirkelz ?

File: cms/src/components/content/EditContentParentValidation.vue (hunk 4 above)
Comment (MrDirkelz) [reply cms/src/components/content/EditContentParentValidation.vue:88]: No, this is not. The cms will most likely not be used on a low-end device that often as well
